#!/bin/bash
# compile and run code

if [[ ! "${1#*.}" == "rs" ]]
then 
   ME="$(basename "$0")"
   echo "Usage: $ME rust-source-file.rs"
   exit 1
fi

TORUN="$(mktemp -t rustx.XXXXXXXXXX)"

SOURCE="$1"
shift 1

rustc -L . -o "$TORUN" "$SOURCE" \
   && exec "$TORUN" $@


